[package]
name = "memoirctl"
version = "0.0.1"
edition = "2021"

[dependencies]
memoir = { path = "../libmemoir" }
anyhow = "1.0.79"
clap = { version = "4.4.16", features = ["derive"] }
thiserror = "1.0.56"
