[package]
name = "memoir"
version = "0.1.0"
edition = "2021"

[dependencies]
interprocess = "1.2.1"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16.0"

[target.'cfg(target_os = "windows")'.dependencies]
# tasklist = "0.2.13"
