name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ubuntu-latest
    - name: pre-commit linters
      run: |
        set -ex
        pip install pre-commit
        # github does not have branch names, and BASE_REF is a name, not a SHA
        git fetch
        if [ -n "$GITHUB_BASE_REF" ]; then
          pre-commit run \
            --verbose \
            --show-diff-on-failure \
            --from-ref=${{ github.event.pull_request.base.sha }} \
            --to-ref=${{ github.event.pull_request.head.sha }}
        else
          pre-commit run \
            --verbose \
            --show-diff-on-failure \
            --all-files
        fi

  build-n-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ matrix.os }}
    - run: cargo build --verbose
    - run: cargo test --verbose
      env:
        RUST_BACKTRACE: 1
